import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/footer/Footer';
import { Header } from '@/components/header/Header';
import './globals.css';
import { nunito } from '@/ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${nunito.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
